### ISSUE TITLE
Possibility to set custom transaction price

### ISSUE THREAD

**Issue by ronnyhaase** [ronnyhaase/solfees.fyi#1]
Eventually with a dropdown where user selects another chain and gas price is fetched live.

**Comment by arihantbansal** [comment]
Wouldn't it be better to look at it from a historical perspective and see what the total USD fees would have been at X point of time?

**Comment by ronnyhaase** [comment]
> Wouldn't it be better to look at it from a historical perspective and see what the total USD fees would have been at X point of time?

What's your thinking? That it would be closer to what you actually spent, considering the buying price of simply from UX?

**Comment by arihantbansal** [comment]
Yes, and also setting a custom price will allow people to speculate price of $SOL which is data manipulation (they can publicly post the false data).

**Comment by ronnyhaase** [comment]
Yeah, a clear messaging and UX is definitely part of this.

But with devtools anyone could change it anyways, same for the Tweet message, since it's editable before getting posted.

**Comment by arihantbansal** [comment]
That's true, then the simpler option is the original idea, to just allow anyone to set a custom SOL price.
