### ISSUE TITLE
Show more data on transaction history

### ISSUE THREAD

**Issue by ronnyhaase** [ronnyhaase/solfees.fyi#15]
- Number of transactions the requested account payed
- Avg fee payed
- ~~Failed transactions (and costs?)~~(failed transactions are skipped by Helius rn)
- Aggregation with chart on transaction types (maybe later)
- Date of first transaction

**Comment by PratikMbade** [comment]
@ronnyhaase  can you please explain the issue in detail  so, I can understand it

**Comment by ronnyhaase** [comment]
A first and quick win would be the transactions the account payed and the avg fee.
If you take a look at the [code here](https://github.com/ronnyhaase/solfees.fyi/blob/16914d742d5859199e26cea03ace3bc1b49a50ab/src/hooks/useTransactions.js#L31) it should be pretty straight forward.

This is how it could look like, but I'd leave it to your or anyone's creativity. Maybe there are also ideas for other useful data.
[![details-draft.png](https://i.postimg.cc/K8Z95YYC/details-draft.png)](https://postimg.cc/crbMx0wc)

@PratikMbade
