### ISSUE TITLE
Add support for Bonfida, ANS and Backpack domains / handles

### ISSUE THREAD

**Issue by ronnyhaase** [ronnyhaase/solfees.fyi#5]

**Comment by arihantbansal** [comment]
We can use https://github.com/onsol-labs/tld-parser for parsing ANS domains, `useDomains` [hook for Bonfida](https://sns.guide/domain-name/react-hooks/use-domains.html).

**Comment by arihantbansal** [comment]
Found a better solution. Just use https://github.com/portalpayments/solana-wallet-names. I'll start working on this.

**Comment by ronnyhaase** [comment]
Portal's SDK was also my preference, but I have no experience with it.
Thanks for looking into it, looking forward to the PR 😉
